---
- name: crontab setup
  hosts: all
  become: yes
  tasks:
  - name: adding crontab
    cron:
      name: Run Test Script
      minute: 30
      hour: 18
      day: 15
      month: "*"
      weekday: "*"
      user: ubuntu
      job: /tmp/script/test.sh
