#---
#- name: Firewall change
#  hosts: all
#  become: yes
#  tasks:
# - name: Enabled a service in firewall
#    firewalld:
#       port: 80/tcp
#       permanent: true
#       state: enabled

#  - name: Reload the firewalld
#    service: 
#      name: firewalld
#      state: reloaded


---
- name: Firewall change
  hosts: all
  become: yes

  tasks:
    - name: Install firewalld
      package:
        name: firewalld
        state: present

    - name: Install python3-firewall
      package:
        name: python3-firewall
        state: present

    - name: Ensure firewalld is running and enabled
      service:
        name: firewalld
        state: started
        enabled: yes

    - name: Enable port 80/tcp in firewall
      firewalld:
        port: 80/tcp
        permanent: true
        state: enabled

#    - name: Reload the firewalld
#      firewalld:
#        state: reloaded
#        immediate: yes

